CREATE TABLE users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name CHAR(60) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE advertisements (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title CHAR(60) NOT NULL,
    user_id SMALLINT UNSIGNED NOT NULL REFERENCES users(id),
    PRIMARY KEY (id)
);